export const AGENTS = [
  {
    name: 'ProfileAgent',
    displayName: 'AI 画像助手',
    role: '画像分析师',
    icon: '🧑',
    bg: 'rgba(108,92,231,0.1)',
    color: '#6C5CE7',
    logMessage: '分析学习画像，确定知识基础与学习偏好',
    status: 'active',
  },
  {
    name: 'PlannerAgent',
    displayName: 'AI 学习规划助手',
    role: '路径规划师',
    icon: '🗺️',
    bg: 'rgba(59,130,246,0.1)',
    color: '#3B82F6',
    logMessage: '规划阶段学习路径，分解核心任务节点',
    status: 'idle',
  },
  {
    name: 'ResourceAgent',
    displayName: 'AI 资源助手',
    role: '资源生成器',
    icon: '📦',
    bg: 'rgba(34,197,94,0.1)',
    color: '#22C55E',
    logMessage: '生成讲义、PPT、思维导图、练习与代码案例',
    status: 'idle',
  },
  {
    name: 'TutorAgent',
    displayName: 'AI 学习导师',
    role: 'AI 导师',
    icon: '🤖',
    bg: 'rgba(249,115,22,0.1)',
    color: '#F97316',
    logMessage: '准备讲解提示与互动问答策略',
    status: 'idle',
  },
  {
    name: 'EvaluateAgent',
    displayName: 'AI 学习评估助手',
    role: '评估引擎',
    icon: '📊',
    bg: 'rgba(236,72,153,0.1)',
    color: '#EC4899',
    logMessage: '初始化评估指标，配置随堂测验与反馈机制',
    status: 'idle',
  },
]
